name: 'build/test and publish'

on: [ pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    # undef VCPKG_ROOT
    env:
      VCPKG_ROOT:
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: |
        npm ci
        npm run bootstrap
        npm run build
      shell: bash
      name: build
    - run: |
        npm run lint
      shell: bash
      name: lint
    - run: |
        npm run test 2>&1
      shell: bash
      name: test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-to-github-registry:
    needs: build
    runs-on: ubuntu-latest
    # Inspired from https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213
    if: contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/heads/prerelease')
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          scope: '@lukka'
      - run: |
          npm ci
          npm run bootstrap
          npm run build
        shell: bash
        name: build
      - run: |
          npm run lint
        shell: bash
        name: lint
      - run: |
          npm run test
        shell: bash
        name: test
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: |
          npm run publish-packages from-package -- --dist-tag=prerelease --registry https://npm.pkg.github.com
        if: contains(github.ref, 'refs/heads/prerelease')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          npm run publish-packages from-package -- --registry https://npm.pkg.github.com
        if: contains(github.ref, 'refs/heads/release')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
