name: 'build'

on:
  pull_request:
    types: [opened, synchronize, edit]
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run bootstrap
        npm run build
      shell: bash
      name: build
    - run: |
        npm run lint
      shell: bash
      name: lint
    - run: |
        npm run test
      shell: bash
      name: test
