name: 'build and publish'

on:
  pull_request:
    types: [opened, synchronize, edit]
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run bootstrap
        npm run build
      shell: bash
      name: build
    - run: |
        npm run lint
      shell: bash
      name: lint
    - run: |
        npm run test
      shell: bash
      name: test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create packages artifacts
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: packages
      if: runner.os == 'Linux'

  publish-to-github-registry:
    needs: build
    runs-on: ubuntu-latest
    # Inspired from https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213
    if: contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/heads/prerelease')
    steps:
      - name: Download NPM package tgz files
        uses: actions/download-artifact@v1
        with:
          name: packages
      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - name: Publish prerelease packages to registry.npmjs.org
        run: npm run publish -- prerelease --dist-tag=prerelease --registry https://registry.npmjs.org
        if: contains(github.ref, 'refs/heads/prerelease')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish release packages to registry.npmjs.org
        run: npm run publish -- patch --registry https://registry.npmjs.org
        if: contains(github.ref, 'refs/heads/release')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
